server:
  port: 8080
  servlet:
    context-path: /food-delivery

spring:
  application:
    name: food-delivery
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fooddeliverydb?createDatabaseIfNotExists=true
    username: root
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            redirectUri: http://localhost:8080/food-delivery/oauth2/callback/{registrationId}
            scope: openid,profile,email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:fb-client-id}
            client-secret: ${FACEBOOK_CLIENT_SECRET:fb-client-secret}
            redirectUri: http://localhost:8080/food-delivery/oauth2/callback/{registrationId}
            scope: email,public_profile
          github:
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            redirectUri: http://localhost:8080/food-delivery/oauth2/callback/{registrationId}
            scope: read:user,user:email
  profiles:
    active: dev

# cors
accessControl:
  allowedOrigin: http://localhost:3000
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  maxAge: 3600
  allowedHeaders: Content-Type
  allowCredentials: true

# security
token:
  expirationms: 3600000
  secret:
    key: vuh6PqHeEV74AagN23BRlV2uEOYvyn2S2C3se2Oj4R6UIVUuxLRXF0m294gq07OjTzPgk6vrq4eX4tcWk5Vbbw==

authorizedRedirectUris: http://localhost:3000/oauth2/redirect
