server:
  port: 8080
  servlet:
    context-path: /food-delivery

spring:
  application:
    name: food-delivery
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fooddeliverydb?createDatabaseIfNotExists=true
    username: root
    password: qpon1234
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1014045813679-f9ss7kvc3uugth4mv8picdmro6uoiqmm.apps.googleusercontent.com
            client-secret: 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
            redirectUri: http://localhost:8080/food-delivery/oauth2/callback/{registrationId}
            scope: openid,profile,email

# cors
accessControl:
  allowedOrigin: "*"
  allowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  maxAge: 3600
  allowedHeaders: "*"

# security
token:
  expirationms: 3600000
  secret:
    key: vuh6PqHeEV74AagN23BRlV2uEOYvyn2S2C3se2Oj4R6UIVUuxLRXF0m294gq07OjTzPgk6vrq4eX4tcWk5Vbbw==

authorizedRedirectUris: http://localhost:3000/oauth2/redirect
